### ISSUE TITLE
curl subprocess stderr is empty string and not None

### ISSUE THREAD

**Issue by aschwanb** [salopensource/sal-scripts#26]
The `--silent` option has been added to `curl` in `utils.py`: https://github.com/salopensource/sal-scripts/blob/master/utils.py#L83 Because of this the following `stderr` will always be of type string and empty:
```python
task = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
(stdout, stderr) = task.communicate()
```

This leads to all `if stderr is not None:` statments beint evaluated as True.

I don't know if this is intended behaviour but it would be good to change the statements to something like `if stderr` to make the behavour more explicit.

**Comment by grahamgilbert** [comment]
This sounds reasonable. I would take a PR to this effect.

**Comment by aschwanb** [comment]
Will do. Looks like it got overlooked in [this pull-request](https://github.com/salopensource/sal-scripts/commit/185f505eae2f114dbd171a183caf09cb7d380c29). I only found it in one place.

Pull request submitted: https://github.com/salopensource/sal-scripts/pull/27
