### ISSUE TITLE
`utils.py` is ambiguous and may collide with other python modules

### ISSUE THREAD

**Issue by 1dustindavis** [salopensource/sal-scripts#40]
The pre/postflight scripts import `utils` from `/usr/local/sal/` by appending that directory to the path: https://github.com/salopensource/sal-scripts/blob/master/payload/usr/local/munki/preflight#L7-L8
https://github.com/salopensource/sal-scripts/blob/master/payload/usr/local/munki/postflight#L7-L8

If a python module is available in the path with the name `utils`, it may break Sal and potentially Munki. Example of ManagedSoftwareUpdate.log on an impacted machine:
```Oct 05 2018 20:42:45 -0700 ### Starting managedsoftwareupdate run: auto ###
Oct 05 2018 20:42:45 -0700 Starting...
Oct 05 2018 20:42:45 -0700     Performing preflight tasks...
Oct 05 2018 20:42:45 -0700     preflight return code: 1
Oct 05 2018 20:42:45 -0700     preflight stderr: Traceback (most recent call last):
  File "/usr/local/munki/preflight", line 19, in <module>
    main()
  File "/usr/local/munki/preflight", line 15, in main
    utils.run_scripts(PREFLIGHT_DIR, sys.argv[1])
AttributeError: 'module' object has no attribute 'run_scripts'
Oct 05 2018 20:42:45 -0700     managedsoftwareupdate run aborted by preflight script: 1
```

This could be resolved by one of the following:
- Rename `utils.py` to a unique name like `salutils.py`
- Change to a relative import with something like `from . import utils`
- Make it a package by adding a `__init__.py` and importing `sal.utils`

**Comment by sheagcraig** [comment]
- Will make a package.

**Comment by eshora** [comment]
For renaming Utils.py to salutils.py are you just renaming it within the folder /usr/local/sal?

**Comment by 1dustindavis** [comment]
@eshora you would also need to modify all references to it, but making it a package is a better solution.

**Comment by eshora** [comment]
Thanks!  When creating a package and the __init__.py file.  Would I just have one line of code stating "import sal.utils"?  Not really sure what to include in the __init__.py file.

**Comment by gregneagle** [comment]
It can be completely empty.
