### ISSUE TITLE
Troubleshooting informations

### ISSUE THREAD

**Issue by simone-pignotti** [salopensource/sal-scripts#65]
Hi,
I have deployed Sal using docker according to https://github.com/salopensource/sal/wiki/Getting-Started (using the latest tags to date) and I have a working munki repo on the same server. Test clients run sal-scripts 2.1.5 and Munki 3.6.4.
I am having issues getting the clients to report: the configuration looks good and the server logs too, but the machine group does not get populated. I tried to restart after setting the preferences SoftwareURL and key, and also to manually run `/usr/local/sal/bin/sal-submit -d` as root, which exits with code 0 producing no output/error at all. Therefore it's very hard to debug what could be going wrong...
Is there a better way to troubleshoot the client/server configuration? Thanks a lot in advance!
Simone

**Comment by simone-pignotti** [comment]
I also tried to add the machine's serial manually in the machine group, ending up with this error when clicking it:
<img width="1485" alt="Screen Shot 2019-11-22 at 12 38 40" src="https://user-images.githubusercontent.com/44410066/69422911-35748080-0d25-11ea-8b09-5a70f527d1d2.png">
<img width="516" alt="Screen Shot 2019-11-22 at 12 38 59" src="https://user-images.githubusercontent.com/44410066/69422924-3ad1cb00-0d25-11ea-83f4-7e17cf4779e3.png">

**Comment by grahamgilbert** [comment]
You shouldn’t use latest unless you are wanting to use a development version. You should use a tagged version. 

Having said that, please pass in the debug environment variable and it will produce a stack trace.

**Comment by sheagcraig** [comment]
@simone-pignotti any updates for us? Still need this issue open?
