### ISSUE TITLE
Version in sal-postflight don't match with Makefile ;)

### ISSUE THREAD

**Issue by jazz-o-mat** [salopensource/sal-scripts#7]
postflight have 0.8.1
Makefile 0.8.0

munki show's 0.8.1

**Comment by grahamgilbert** [comment]
Because 0.8.1 isn't out yet ;)

**Comment by jazz-o-mat** [comment]
hmm, my fault
not munki, sal show 0.8.1 in the sal version plugin

**Comment by grahamgilbert** [comment]
You built the package or used the one that's posted on the releases page? You should not and do not need to build from source.

**Comment by jazz-o-mat** [comment]
Yes, i have build from source, have not checked whether a change has happened. I work with branches, so I have not checked. ;)
