### ISSUE TITLE
M1 Processors aren't recognised

### ISSUE THREAD

**Issue by grahamgilbert** [salopensource/sal-scripts#92]
<img width="556" alt="Screen Shot 2020-12-07 at 12 25 38 PM" src="https://user-images.githubusercontent.com/1208495/101401613-77685a00-3887-11eb-9a96-d88328d56f0e.png">

**Comment by sheagcraig** [comment]
I grabbed the macadmins relocatable python and ran system_profiler and you get different results; I'm putting together a PR to update the python and go universal and then handle the differing output formats.
